image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

cache:
  paths:
    - node_modules/

stages:
  - test

lint-and-test:
  stage: test
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d mysql
    - DOTENV=.env.local npx jest