name: Test

on: [push, pull_request]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d mysql

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npx jest
      env:
        DB_HOST: localhost
        DB_USER: kevin
        DB_PASSWORD: 123
        DB_PORT: 3306
        DB_NAME: tododb
        MYSQL_LOG: 1
        PORT: 9000



    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
